### ISSUE TITLE
Deploy MedAssistant project

### ISSUE THREAD

**Issue by schneider001** [schneider001/MedAssistant02#2]
- [x] Разобраться, как запускать приложение с DEBUG = False в settings.py (нужно статические файлы подтягивать с помощью whitenoise, ссылка на туториал: https://www.w3schools.com/django/django_collect_static_files.php) 
- [x] Настроить деплой в веб-сервере gunicorn
- [x] Настроить деплой в контейнере Docker
- [x] Настроить постоянное хранение данных картинок и бд в volumes

**Comment by schneider001** [comment]
Для запуска приложения Django, использующего **WebSocket**,  с помощью _gunicorn_ с несколькими workers необходимо:
1. Установить _gunicorn_, модуль python _uvicorn_, _redis_
2. В _settings.py_ добавить
`CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
        },
    },
}`
3. Запуск командой **gunicorn medassistant.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers 3**

**Comment by Wesdcv** [comment]
## Оптимизация Docker и настройка Django

### Задачи:

#### 1. Docker:
- [x] **Перевести базовый образ на Debian 12**
- [x] **Сделать chown не рекурсивным** и, по возможности, перенести в Dockerfile
- [x] **Оптимизация времени сборки**: перенести слои COPY максимально вперед
- [x] **Объявление Volume до Run?** Рассмотреть возможность объявления Volume до команды Run
- [x] **Сделать порт (PORT) переменной окружения** и поставить его рядом с командой EXPOSE

#### 2. Postgres:
- [x] **Создание пользователя www-data**: сделать его владельцем нашей БД и производить все операции по подключению к сокету Postgres от его имени

#### 3. Скрипт:
- [x] Вместо открытия Firefox **выводить адрес для подключения**

#### 4. Django:
- [x] **Разрешить подключение с любого хоста**: установить значение `ALLOWED_HOSTS = ['*']`
- [ ] ~~**Отдавать статические файлы только аутентифицированному пользователю**~~
- [ ] **Перенести model в корень** и настроить импорт как приложение Django, подобно app_medassistent

**Comment by Wesdcv** [comment]
- [x] **Учесть возможность применения миграций при существующей базе данных**
- [ ] ~~**Проводить UNIX-общение с БД через пользователя postgres**~~ - _конфликтует с предыдущей задачей_
- [x] **shellcheck**: проверить и доработать существующие bash-команды

**Comment by Wesdcv** [comment]
Все текущие задачи решены, не планируются к решению либо требуют дополнительных работ со стороны участников проекта. Закрываю issue до востребования.
